import React from "react";
import { LegalPage } from "./terms";

export default function VendorAgreementScreen() {
  return (
    <LegalPage
      title="Vendor Agreement"
      subtitle="This Vendor Agreement is entered into between Ehimare Co and the vendor using the Eki platform. By creating a Vendor Account or listing products on Eki, you agree to be bound by this Agreement."
      canonicalUrl="https://culinarytales.app/vendor-agreement"
      sections={[
        ["1. Purpose", "Eki provides software and business tools that enable vendors to list products, receive orders, manage customers, send promotional offers, track sales and analytics, and operate their business more efficiently.\n\nEki is a technology platform and is not the seller of products listed by vendors."],
        ["2. Vendor Eligibility", "To use Eki as a vendor you must:\n• Be at least 18 years old.\n• Provide accurate information.\n• Complete identity verification when requested.\n• Have the legal right to sell the products you list.\n• Comply with all applicable laws.\n\nEki may refuse, suspend, or terminate vendor access at its discretion."],
        ["3. Vendor Verification", "Vendor verification may include government-issued identification, business information, address verification, and additional checks required by Eki.\n\nVerification must be completed before access to certain platform services is granted.\n\nProviding false information may result in immediate account suspension."],
        ["4. Vendor Responsibilities", "Vendors are solely responsible for product quality, product descriptions, product pricing, inventory accuracy, packaging, shipping, customer service, compliance with food safety laws, and compliance with import and export regulations.\n\nEki does not inspect or guarantee products listed by vendors."],
        ["5. Product Listings", "Vendors must ensure all listings are accurate, lawful, do not mislead buyers, and contain correct pricing and product information.\n\nEki reserves the right to remove any listing at any time."],
        ["6. Prohibited Products", "Vendors may not sell illegal products, counterfeit products, restricted or controlled substances, dangerous goods prohibited by law, or any item prohibited by Eki policies.\n\nViolation may result in immediate removal and account termination."],
        ["7. Orders", "When a buyer places an order, the vendor is responsible for fulfilling the order, shipping or delivering within a reasonable timeframe, and keeping order status updated.\n\nFailure to fulfil orders may result in account restrictions."],
        ["8. Africa-Based Vendor Payment Protection", "For vendors located in Africa, Eki may operate a payment protection process for eligible transactions.\n\nUnder this process:\n• Buyer funds may be temporarily held.\n• Funds may be released after successful delivery confirmation.\n• Funds may be released after successful OTP verification.\n• Funds may be released automatically after the applicable review period.\n\nThe vendor agrees that Eki may delay release of funds while delivery status is being verified."],
        ["9. OTP Delivery Verification", "For transactions using OTP verification:\n• An OTP may be generated by Eki.\n• The OTP may be used to confirm delivery.\n• Successful OTP confirmation may trigger release of funds.\n\nFraudulent attempts to manipulate the OTP process may result in permanent suspension."],
        ["10. Customer Marketing Features", "Eki may provide tools allowing vendors to contact previous buyers, send offers, promote products, and re-engage inactive customers.\n\nVendors agree not to send misleading messages, not to harass customers, not to abuse marketing tools, and to comply with applicable marketing laws.\n\nEki may suspend access to marketing features where misuse is detected."],
        ["11. Vendor Subscription", "Vendors may receive a limited free usage period. Following the free period, continued access may require an active subscription.\n\nSubscription fees are billed in advance, are non-refundable except where required by law, and may be changed with reasonable notice.\n\nFailure to maintain an active subscription may restrict access to platform services."],
        ["12. Platform Fees", "Eki may charge subscription fees, transaction fees, and service fees.\n\nApplicable fees will be disclosed within the platform. The Vendor authorises Eki to deduct applicable fees where permitted."],
        ["13. Customer Relationships", "Customers acquired through Eki remain customers of the Vendor.\n\nHowever, Eki retains ownership of the Eki platform, platform technology and infrastructure. Vendors may not copy, scrape, or misuse platform data."],
        ["14. Vendor Conduct", "Vendors must not engage in fraud, manipulate reviews, mislead buyers, circumvent platform processes, abuse other users, or use Eki for unlawful activities.\n\nViolations may result in suspension or termination."],
        ["15. Suspension And Termination", "Eki may suspend or terminate vendor accounts for fraud, verification failures, policy violations, abuse of customers, repeated customer complaints, or non-payment of subscription fees.\n\nTermination may result in removal of listings and restricted platform access."],
        ["16. Intellectual Property", "All Eki branding, software, systems, content, and technology remain the property of Ehimare Co.\n\nNothing in this Agreement transfers ownership of Eki intellectual property to vendors."],
        ["17. Limitation Of Liability", "To the maximum extent permitted by law, Eki shall not be liable for lost profits, product defects, shipping delays, customer disputes, business interruption, or indirect or consequential damages.\n\nEki provides software and technology services only."],
        ["18. Indemnity", "The Vendor agrees to indemnify and hold harmless Ehimare Co from claims arising from products sold, vendor conduct, regulatory violations, customer disputes, or breach of this Agreement."],
        ["19. Changes To This Agreement", "Eki may update this Agreement from time to time. Continued use of the platform constitutes acceptance of updated terms."],
        ["20. Governing Law", "This Agreement shall be governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.\n\nContact: Ehimare Co, United Kingdom\nEmail: info@culinarytales.app"],
      ]}
    />
  );
}
